apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cli-plugin-support
  description: Ease support tasks within the VTEX ecosystem
  tags:
    - typescript
    - oclif
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex/cli-plugin-support
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: JW011RIB
    vtex.com/platform-flow-id: Merch#3,CommDev#1
spec:
  lifecycle: stable
  owner: te-0029
  type: cli-plugin
  dependsOn: []
  subcomponentOf: toolbelt
