name: ci

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - '**'
jobs:
  prepack:
      name: prepack
      runs-on: ubuntu-latest
      steps: 
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install
      - name: Update README
        run: yarn prepack
      - name: Remove collor char from README
        run: curl 'https://vtex-toolbelt-test.s3.us-east-2.amazonaws.com/removeTerminalCollorFromFile.sh' > tmpCollorScrip.sh && bash tmpCollorScrip.sh && rm tmpCollorScrip.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "Automatic update on Toolbelt plugin documentation"
          add: "README.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}